// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALedzmW5vL_4PymkkaH8xHIortoq8f4iA',
    appId: '1:951499706276:web:95e12039f7fdb418aebb31',
    messagingSenderId: '951499706276',
    projectId: 'intime-notifications',
    authDomain: 'intime-notifications.firebaseapp.com',
    storageBucket: 'intime-notifications.firebasestorage.app',
    measurementId: 'G-BK35X03Z1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBQcdxOpQNmqZ14zB6yIwUtlSGqi4K-mg',
    appId: '1:951499706276:android:b5a65b9dbe175b48aebb31',
    messagingSenderId: '951499706276',
    projectId: 'intime-notifications',
    storageBucket: 'intime-notifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfVvsEnF-2Rd3l3dVvDuf1J_jRS1dPYkk',
    appId: '1:951499706276:ios:59b14973e2d07f65aebb31',
    messagingSenderId: '951499706276',
    projectId: 'intime-notifications',
    storageBucket: 'intime-notifications.firebasestorage.app',
    iosBundleId: 'com.example.inTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfVvsEnF-2Rd3l3dVvDuf1J_jRS1dPYkk',
    appId: '1:951499706276:ios:59b14973e2d07f65aebb31',
    messagingSenderId: '951499706276',
    projectId: 'intime-notifications',
    storageBucket: 'intime-notifications.firebasestorage.app',
    iosBundleId: 'com.example.inTime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALedzmW5vL_4PymkkaH8xHIortoq8f4iA',
    appId: '1:951499706276:web:7555b262b4f2ddbdaebb31',
    messagingSenderId: '951499706276',
    projectId: 'intime-notifications',
    authDomain: 'intime-notifications.firebaseapp.com',
    storageBucket: 'intime-notifications.firebasestorage.app',
    measurementId: 'G-VPKF9L6TTE',
  );
}
